@ApiHost = http://localhost:5109

### Authenticate
< {%
    client.global.clear("auth_token");
%}
POST {{ApiHost}}/auth
Accept: application/json
Content-Type: application/json

{
  "Email": "user1@email.com",
  "Password": "123"
}

> {%
    client.assert(response.status === 200);
    client.global.set("auth_token", response.body.token.toString());
%}

###

### Get activity
GET {{ApiHost}}/activity
Authorization: Bearer {{auth_token}}

> {%
    client.assert(response.status === 200);
%}

###
